<script lang="ts">
    import {     
        Diagram, polygon, line, curve, empty, text, diagram_combine,
        Vector2, V2, Vdir,
        from_degree, linspace, range, array_repeat,
        linspace_exc, range_inc,

        draw_to_svg,
        default_diagram_style, default_text_diagram_style, default_textdata,
        _init_default_diagram_style, _init_default_text_diagram_style, _init_default_textdata,
        rectangle, square, regular_polygon, regular_polygon_side, circle, arc,
        arrow, arrow2, textvar,
        str_to_mathematical_italic,
        Interactive,
        axes_transform, ax, axes_empty, axes_corner_empty,
        xtickmark_empty, xtickmark, xticks,
        ytickmark_empty, ytickmark, yticks,
        xyaxes, xygrid, xycorneraxes,
        plot, plotv, plotf, under_curvef,
        align_vertical, align_horizontal,
        distribute_horizontal, distribute_vertical,
        distribute_horizontal_and_align, distribute_vertical_and_align, 


        annotation,
        mechanics,
        mod,
    } from 'diagramatics'
    // `text()` is overwritten by something that is generated by svelte
    // fix it with some hack
    import { text as dgtext } from 'diagramatics'
    let HACK_FOR_DIAGRAMATICS_IMPORT = [
        dgtext,

        Diagram, polygon, line, curve, empty, text, diagram_combine,
        Vector2, V2, Vdir,
        from_degree, linspace, range, array_repeat,
        linspace_exc, range_inc,

        draw_to_svg,
        default_diagram_style, default_text_diagram_style, default_textdata,
        _init_default_diagram_style, _init_default_text_diagram_style, _init_default_textdata,
        rectangle, square, regular_polygon, regular_polygon_side, circle, arc,
        arrow, arrow2, textvar,
        str_to_mathematical_italic,
        Interactive,
        axes_transform, ax, axes_empty, axes_corner_empty,
        xtickmark_empty, xtickmark, xticks,
        ytickmark_empty, ytickmark, yticks,
        xyaxes, xygrid, xycorneraxes,
        plot, plotv, plotf, under_curvef,

        align_vertical, align_horizontal,
        distribute_horizontal, distribute_vertical,
        distribute_horizontal_and_align, distribute_vertical_and_align, 

        annotation,
        mechanics,
        mod,
    ]

    import { onMount } from 'svelte';
    import { parse_content } from './codeformatutils'

    export let width  : number = 300;
    export let height : number = 300;
    export let margin_right : number = 20;

    // ======================== code

    let diagram_svg : SVGSVGElement;
    let control_container : HTMLDivElement;
    let content_div : HTMLDivElement;

    onMount(() => {
        // diagramatics helper function
        let draw = (...diagrams : Diagram[]) => {
            draw_to_svg(diagram_svg, diagram_combine(...diagrams));
        };

        let int = new Interactive(control_container, diagram_svg);

        // reset default styles
        for (let s in default_diagram_style) 
            (default_diagram_style as any)[s] = (_init_default_diagram_style as any)[s];
        for (let s in default_text_diagram_style)
            (default_text_diagram_style as any)[s] = (_init_default_text_diagram_style as any)[s];
        for (let s in default_textdata)
            (default_textdata as any)[s] = (_init_default_textdata as any)[s];


        let content = parse_content(content_div.innerHTML);
        try {
            // `text()` is overwritten by something that is generated by svelte
            // fix it with some hack
            let text = dgtext;
            eval(content);
        } catch (e) {
            diagram_svg.outerHTML = (e as Error).toString();
            console.warn(e);
        }

        // delete `control_container` if it's empty
        if (Object.keys(int.inp_variables).length == 0) {
            // delete controlelem if it's empty
            control_container.outerHTML = '';
        }

        // =================== hack
        // hack to make svelte not remove the unused variables
        // because we're using `eval` here
        let x = Math.random();
        if (x+1 == x) console.log(draw, HACK_FOR_DIAGRAMATICS_IMPORT);
        // =================== hack
    });
</script>

<div class="example-diagram">
    <svg bind:this={diagram_svg} class="svg-diagram" 
             style="width: {width}px; height: {height}px; margin-right: {margin_right}px"></svg>
    <div bind:this={control_container} class="control-container"> </div>
</div>
<div bind:this={content_div} style="display:none"> 
    <slot/>
</div>


<style>
.control-container {
    margin-left: 20px;
    margin-bottom: 100px;
}
.example-diagram {
    display: inline-block;
}
</style>

